# Generated by Django 4.2.23 on 2025-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subsciber',
            new_name='subscribe',
        ),
    ]
