# Generated by Django 4.2.23 on 2025-08-14 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_subsciber_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='Subscibed_at',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscibed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
